language: node_js
node_js: "14.16"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    - "ENVIRONMENT=production"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-group1
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-group2
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-group3
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-group4
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-group5
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-website-deployment-tool notify-started

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    # GROUP 1
    - <<: *production-job
      stage: production-group1
      name: IP Service
      script: scripts/deploy.js ip

    - <<: *production-job
      stage: production-group1
      name: Locale Service
      script: scripts/deploy.js locale

    - <<: *production-job
      stage: production-group1
      name: Mailer Service
      script: scripts/deploy.js mailer

    - <<: *production-job
      stage: production-group1
      name: Token Service
      script: scripts/deploy.js token

    - <<: *production-job
      stage: production-group1
      name: Organization Service
      script: scripts/deploy.js organization

    # GROUP 2
    - <<: *production-job
      stage: production-group2
      name: User Service
      script: scripts/deploy.js user

    - <<: *production-job
      stage: production-group2
      name: Application Service
      script: scripts/deploy.js application

    # GROUP 3
    - <<: *production-job
      stage: production-group3
      name: Export Service
      script: scripts/deploy.js export

    - <<: *production-job
      stage: production-group3
      name: Membership Service
      script: scripts/deploy.js membership

    # GROUP 4
    - <<: *production-job
      stage: production-group4
      name: GraphQL Service
      script: scripts/deploy.js graphql

    # GROUP 5
    - <<: *production-job
      stage: production-group5
      name: Manage UI Service
      script: scripts/deploy.js manage

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-website-deployment-tool notify-finished
